# Generated by Django 3.1.1 on 2020-09-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='markdown',
            field=models.TextField(default='# Hello WOrld!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='placeholder_thumbnail.png', upload_to='thumbnail'),
        ),
    ]
