# Generated by Django 3.1.1 on 2020-09-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200919_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='markdown',
            new_name='content_html',
        ),
    ]
